import {STORE_NAME} from "./accountReducer";

export const FETCH_ACCOUNT_REQUESTED = STORE_NAME + 'FETCH_ACCOUNT_REQUESTED';
export const FETCH_ACCOUNT_SUCCESS = STORE_NAME + 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = STORE_NAME + 'FETCH_ACCOUNT_ERROR';